# Generated by Django 2.0.7 on 2018-07-30 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='随笔', max_length=128, null=True, verbose_name='标题')),
                ('summary', models.CharField(blank=True, max_length=128, null=True, verbose_name='摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('total_like', models.PositiveIntegerField(db_index=True, default=0, verbose_name='喜欢数')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='阅读数')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(blank=True, max_length=128, null=True, verbose_name='收录专题')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('user_like', models.ManyToManyField(blank=True, related_name='liked_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('-created',),
            },
        ),
    ]
