# Generated by Django 2.0.7 on 2018-08-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0002_remove_article_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='image/article'),
        ),
    ]
