# Generated by Django 2.0.7 on 2018-08-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0003_article_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='avatar',
        ),
        migrations.AddField(
            model_name='article',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='image/article', verbose_name='封面图片'),
        ),
    ]
