# Generated by Django 2.0.7 on 2018-07-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20180730_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='record_article',
            new_name='recorded',
        ),
    ]
