# Generated by Django 2.0.7 on 2018-07-31 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20180730_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writing.Article', verbose_name='被收录文章'),
        ),
        migrations.AlterField(
            model_name='recordarticle',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic', verbose_name='收录所在专题'),
        ),
    ]
