# Generated by Django 2.0.7 on 2018-07-31 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_following_user'),
        ('actions', '0002_auto_20180730_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followtopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='followtopic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='user_from',
        ),
        migrations.RemoveField(
            model_name='followuser',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='FollowTopic',
        ),
        migrations.DeleteModel(
            name='FollowUser',
        ),
    ]
