# Generated by Django 2.0.7 on 2018-07-31 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20180731_0012'),
        ('users', '0002_remove_userprofile_following_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_topic_set', to='topics.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_user_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '关注专题',
                'verbose_name_plural': '关注专题',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='FollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '关注用户',
                'verbose_name_plural': '关注用户',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_topic',
            field=models.ManyToManyField(related_name='followers_topic', through='users.FollowTopic', to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_user',
            field=models.ManyToManyField(related_name='followers_user', through='users.FollowUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
