# Generated by Django 2.0.7 on 2018-08-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180731_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(blank=True, default='这家伙很懒，什么都没有留下！', max_length=128, null=True, verbose_name='座右铭'),
        ),
    ]
