# Generated by Django 2.0.7 on 2018-08-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180803_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='image/default.jpg', upload_to='image/%Y%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(blank=True, default='这家伙很懒，什么都没有留下！', max_length=128, null=True, verbose_name='个性签名'),
        ),
    ]
