# Generated by Django 2.0.7 on 2018-09-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180830_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openid',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='oauth_id'),
        ),
    ]
